//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio12_03_16.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusParaFahrenheit", ReplyAction="*")]
        float CelsiusParaFahrenheit(float temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusParaFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<float> CelsiusParaFahrenheitAsync(float temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitParaCelsius", ReplyAction="*")]
        float FahrenheitParaCelsius(float temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitParaCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<float> FahrenheitParaCelsiusAsync(float temperatura);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Exercicio12_03_16.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Exercicio12_03_16.ServiceReference1.WebServiceSoap>, Exercicio12_03_16.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float CelsiusParaFahrenheit(float temperatura) {
            return base.Channel.CelsiusParaFahrenheit(temperatura);
        }
        
        public System.Threading.Tasks.Task<float> CelsiusParaFahrenheitAsync(float temperatura) {
            return base.Channel.CelsiusParaFahrenheitAsync(temperatura);
        }
        
        public float FahrenheitParaCelsius(float temperatura) {
            return base.Channel.FahrenheitParaCelsius(temperatura);
        }
        
        public System.Threading.Tasks.Task<float> FahrenheitParaCelsiusAsync(float temperatura) {
            return base.Channel.FahrenheitParaCelsiusAsync(temperatura);
        }
    }
}
